---
title: 'p8105_hw6_fw2334'
author: "Frances Williams"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelr)
library(mgcv)
```

### Problem 1

Importing and tidying data
```{r}
birthweight_data = read_csv(file = "./files/birthweight.csv") %>% 
  mutate(
    babysex = factor(babysex, levels = c(1,2), labels = c("male", "female")),
    frace = factor(frace, levels = c(1,2,3,4,8,9), labels = c("white", "black", "asian", "puerto rican", "other", "unkown")),
    malform = factor(malform, levels = c(0,1), labels = c("absent", "present")),
    mrace = factor(mrace, levels = c(1,2,3,4,8), labels = c("white", "black", "asian", "puerto rican", "other"))
  )
```

Modeling
```{r}
set.seed(1)

model1 = lm(bwt ~ ppbmi + gaweeks + smoken + malform, data = birthweight_data)

model1 %>% 
  broom::tidy()

bw_res_pred = birthweight_data %>% 
  modelr::add_residuals(model1) %>% 
  modelr::add_predictions(model1) 

bw_res_pred %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()

```

Other model comparisons
```{r}
model2 = lm(bwt ~ blength + gaweeks, data = birthweight_data)

bw_respred_m2 = birthweight_data %>% 
  modelr::add_residuals(model2) %>% 
  modelr::add_predictions(model2) 

bw_respred_m2 %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()


model3 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = birthweight_data)
```

#### Cross validation
```{r}

cv_df = crossv_mc(data = birthweight_data, n = 100)

cv_df = 
  cv_df %>% 
  mutate(mod1 = map(train, ~lm(bwt ~ gaweeks + babysex + bhead, data = .x)),
         mod2 = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         mod3 = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = as_tibble(.x)))) %>% 
  mutate(rmse_mod1 = map2_dbl(mod1, test, ~rmse(model = .x, data = .y)),
         rmse_mod2 = map2_dbl(mod2, test, ~rmse(model = .x, data = .y)),
         rmse_mod3 = map2_dbl(mod3, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

```

# Problem 2

```{r message = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
set.seed(1)

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps = 
  tibble(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )


bootstrap_results = boot_straps %>% 
  mutate(
    models = map(strap_sample, ~ lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>%
  unnest(cols = c(results)) %>% 
  select(strap_number, term, estimate, models) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate) %>% 
  janitor::clean_names() %>% 
  rename(b0 = intercept, b1 = tmin) %>% 
  mutate(
    log_b0b1 = log(b0*b1),
    r2 = map(models, broom::glance)) %>%
  unnest(cols = c(r2))
  
  
```

